// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Xyz
{
    public static class DataSource
    {
        public static Task<DataSourceResult> InvokeAsync(DataSourceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<DataSourceResult>("xyz:index/dataSource:DataSource", args ?? new DataSourceArgs(), options.WithDefaults());

        public static Output<DataSourceResult> Invoke(DataSourceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<DataSourceResult>("xyz:index/dataSource:DataSource", args ?? new DataSourceInvokeArgs(), options.WithDefaults());

        public static Output<DataSourceResult> Invoke(DataSourceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<DataSourceResult>("xyz:index/dataSource:DataSource", args ?? new DataSourceInvokeArgs(), options.WithDefaults());
    }


    public sealed class DataSourceArgs : global::Pulumi.InvokeArgs
    {
        [Input("sampleAttribute", required: true)]
        public string SampleAttribute { get; set; } = null!;

        public DataSourceArgs()
        {
        }
        public static new DataSourceArgs Empty => new DataSourceArgs();
    }

    public sealed class DataSourceInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sampleAttribute", required: true)]
        public Input<string> SampleAttribute { get; set; } = null!;

        public DataSourceInvokeArgs()
        {
        }
        public static new DataSourceInvokeArgs Empty => new DataSourceInvokeArgs();
    }


    [OutputType]
    public sealed class DataSourceResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string SampleAttribute;

        [OutputConstructor]
        private DataSourceResult(
            string id,

            string sampleAttribute)
        {
            Id = id;
            SampleAttribute = sampleAttribute;
        }
    }
}
