name: Verify release
description: Ensures a release is usable.

inputs:
  language:
    description: The language to test against. One of `nodejs`, `python`, `dotnet`, `go` or `java`.
    required: true
  directory:
    description: Path to a Pulumi program to use for the test.
    required: true
  version:
    description: The version of the provider to be tested.
    required: true

runs:
  using: "composite"
  steps:
    - name: Initialize stack
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: pulumi stack init ${{ inputs.language }}-${{ inputs.version }}

    - name: Install nodejs package
      if: inputs.language == 'nodejs'
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        npm uninstall "@pulumi/xyz" | true
        npm install "@pulumi/xyz@v${{ inputs.version }}"

    - name: Install provider
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: pulumi install

    - name: Preview
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: pulumi preview
