// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.xyz.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class DataSourcePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final DataSourcePlainArgs Empty = new DataSourcePlainArgs();

    @Import(name="sampleAttribute", required=true)
    private String sampleAttribute;

    public String sampleAttribute() {
        return this.sampleAttribute;
    }

    private DataSourcePlainArgs() {}

    private DataSourcePlainArgs(DataSourcePlainArgs $) {
        this.sampleAttribute = $.sampleAttribute;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DataSourcePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DataSourcePlainArgs $;

        public Builder() {
            $ = new DataSourcePlainArgs();
        }

        public Builder(DataSourcePlainArgs defaults) {
            $ = new DataSourcePlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder sampleAttribute(String sampleAttribute) {
            $.sampleAttribute = sampleAttribute;
            return this;
        }

        public DataSourcePlainArgs build() {
            if ($.sampleAttribute == null) {
                throw new MissingRequiredPropertyException("DataSourcePlainArgs", "sampleAttribute");
            }
            return $;
        }
    }

}
