// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package xyz

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-xyz/sdk/go/xyz/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func DataSource(ctx *pulumi.Context, args *DataSourceArgs, opts ...pulumi.InvokeOption) (*DataSourceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv DataSourceResult
	err := ctx.Invoke("xyz:index/dataSource:DataSource", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking DataSource.
type DataSourceArgs struct {
	SampleAttribute string `pulumi:"sampleAttribute"`
}

// A collection of values returned by DataSource.
type DataSourceResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id              string `pulumi:"id"`
	SampleAttribute string `pulumi:"sampleAttribute"`
}

func DataSourceOutput(ctx *pulumi.Context, args DataSourceOutputArgs, opts ...pulumi.InvokeOption) DataSourceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (DataSourceResultOutput, error) {
			args := v.(DataSourceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("xyz:index/dataSource:DataSource", args, DataSourceResultOutput{}, options).(DataSourceResultOutput), nil
		}).(DataSourceResultOutput)
}

// A collection of arguments for invoking DataSource.
type DataSourceOutputArgs struct {
	SampleAttribute pulumi.StringInput `pulumi:"sampleAttribute"`
}

func (DataSourceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DataSourceArgs)(nil)).Elem()
}

// A collection of values returned by DataSource.
type DataSourceResultOutput struct{ *pulumi.OutputState }

func (DataSourceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DataSourceResult)(nil)).Elem()
}

func (o DataSourceResultOutput) ToDataSourceResultOutput() DataSourceResultOutput {
	return o
}

func (o DataSourceResultOutput) ToDataSourceResultOutputWithContext(ctx context.Context) DataSourceResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o DataSourceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v DataSourceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o DataSourceResultOutput) SampleAttribute() pulumi.StringOutput {
	return o.ApplyT(func(v DataSourceResult) string { return v.SampleAttribute }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(DataSourceResultOutput{})
}
