name: "Test"

on:
  workflow_call:
    inputs:
      version:
        description: "The version of the provider to test"
        required: true
        type: string

jobs:
  test:
    name: Test
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        language:
          - nodejs
          - python
          - dotnet
          - go
          - java
    runs-on: ubuntu-latest
    env:
      PROVIDER_VERSION: ${{ inputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Test setup
        uses: ./.github/actions/test-setup
        with:
          language: ${{ matrix.language }}
      - name: Run tests
        run:
          cd examples && go test -v -json -count=1 -cover -timeout 2h -tags=${{
          matrix.language }} -skip TestPulumiExamples -parallel 4 . 2>&1 | tee /tmp/gotest.log | gotestfmt
