name: "Verify Release"

on:
  pull_request:
    paths-ignore:
    - CHANGELOG.md

env:
  PULUMI_API: https://api.pulumi-staging.io
  PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
  PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
  PULUMI_MISSING_DOCS_ERROR: "true"
  TF_APPEND_USER_AGENT: pulumi
  XYZ_REGION: us-west-2
  MISE_WINDOWS_EXECUTABLE_EXTENSIONS: ",exe,bat,cmd,com,ps1,vbs"

jobs:
  verify-release:
    name: verify-release
    strategy:
      matrix:
        runner: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Configure Git to checkout files with long names
        run: git config --global core.longpaths true
      - name: Checkout Repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false      
      - env:
          ESC_ACTION_ENVIRONMENT: github-secrets/${{ github.repository_owner }}-${{ github.event.repository.name }}
          ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: "false"
          ESC_ACTION_OIDC_AUTH: "true"
          ESC_ACTION_OIDC_ORGANIZATION: pulumi
          ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
        id: esc-secrets
        name: Fetch secrets from ESC
        uses: pulumi/esc-action@9eb774255b1a4afb7855678ae8d4a77359da0d9b
      - name: Provide bash shim for mise
        if: matrix.runner == 'windows-latest'
        shell: pwsh
        run: |
          $bash = "${env:ProgramFiles}\Git\bin\bash.exe"
          if (!(Test-Path $bash)) { throw "Git Bash missing" }
          $shim = Join-Path $env:RUNNER_TEMP "mise-shims"
          New-Item -ItemType Directory -Force -Path $shim | Out-Null
          Copy-Item $bash (Join-Path $shim "bash") -Force
          Add-Content -Path $env:GITHUB_PATH -Value $shim

      - name: Setup mise
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cache_key: "mise-{{platform}}-{{file_hash}}"
          cache: false
          # only saving the cache in the prerequisites job
          cache_save: false
